### ISSUE TITLE
ERROR The stream is of a different type than handled by this element.

### ISSUE THREAD

**Issue by matmunn** [nilicule/mopidy-audioaddict#6]
Any time I try to play a Digitally Imported stream from AudioAddict in the log I get "ERROR The stream is of a different type than handled by this element."
I have gstreamer0.10-plugins-bad, gstreamer0.10-plugins-ugly and gstreamer0.10-ffmpeg installed and everything is at the newest versions.

**Comment by toni-sissala** [comment]
I'm having same symptoms on all AudioAddict streams.  Help?

**Comment by nilicule** [comment]
Thanks for the patch, @matmunn!
